# Generated by Django 4.1.6 on 2023-05-11 01:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.IntegerField(max_length=11)),
                ('idade', models.IntegerField(max_length=5)),
                ('numero', models.IntegerField(max_length=19)),
            ],
        ),
    ]
