# Generated by Django 4.1.6 on 2023-05-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuario', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
                ('Cliente_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente_Usuario', to='Myapp.cliente')),
            ],
        ),
    ]
