# Generated by Django 4.1.6 on 2023-05-13 21:16

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(upload_to=Myapp.models.upload_image),
        ),
    ]
