# Generated by Django 4.1.6 on 2023-05-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_usuario_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagem',
        ),
    ]
