# Generated by Django 4.1.6 on 2023-05-14 01:34

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_remove_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default=1, upload_to=Myapp.models.upload_image),
            preserve_default=False,
        ),
    ]
