# Generated by Django 4.1.6 on 2023-05-15 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myapp', '0005_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Usuario_superUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.FloatField(max_length=19),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.FloatField(max_length=11),
        ),
    ]
