# Generated by Django 4.1.6 on 2023-05-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_usuario_usuario_superuser_alter_cliente_idade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_superUser',
        ),
    ]
