# Generated by Django 4.1.6 on 2023-05-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_usuario_usuario_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_superUser',
        ),
    ]
