# Generated by Django 4.1.6 on 2023-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_remove_usuario_usuario_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Cliente_usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Cliente_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Cliente', to='Myapp.usuario'),
            preserve_default=False,
        ),
    ]
