# Generated by Django 4.1.6 on 2023-05-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_remove_usuario_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Cliente_usuario',
            new_name='Usuario_Cliente',
        ),
    ]
