# Generated by Django 4.1.6 on 2023-05-19 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_rename_cliente_usuario_cliente_usuario_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id_transacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(default='0', max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=1000, validators=[django.core.validators.MinValueValidator(0.0, message='O valor deve ser no minimo 0.00'), django.core.validators.MaxValueValidator(1000000)])),
                ('data_trasacao', models.DateField(auto_now=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.cliente')),
            ],
        ),
    ]
