# Generated by Django 4.1.6 on 2023-05-19 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_transacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10000, validators=[django.core.validators.MinValueValidator(0.0, message='O valor deve ser no minimo 0.00'), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
