# Generated by Django 4.1.6 on 2023-05-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_alter_transacoes_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='codigo',
            field=models.CharField(default=False, max_length=10000),
        ),
    ]
