# Generated by Django 4.1.6 on 2023-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0020_transacoes_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10000),
            preserve_default=False,
        ),
    ]
