# Generated by Django 4.1.6 on 2023-05-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0021_cliente_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='saldo',
        ),
    ]
