# Generated by Django 4.1.6 on 2023-05-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_remove_cliente_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacoes',
            name='saldo',
        ),
    ]
