# Generated by Django 4.1.6 on 2023-05-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_remove_transacoes_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('Cliente_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente_Endereco', to='Myapp.cliente')),
            ],
        ),
    ]
