# Generated by Django 4.1.6 on 2023-05-25 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0024_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=25)),
                ('saldoBancario', models.CharField(max_length=100000)),
            ],
        ),
    ]
