# Generated by Django 4.1.6 on 2023-05-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0025_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='Cliente_Conta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Conta_Cliente', to='Myapp.cliente'),
            preserve_default=False,
        ),
    ]
