# Generated by Django 4.1.6 on 2023-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0026_conta_cliente_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldoBancario',
            field=models.FloatField(default=0, max_length=100000),
        ),
    ]
